name: Cache Dependencies Example

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Prime cache 605c345
        id: prime-cache-605c345    # ⚠ Make sure the ID is exactly this
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: cache-605c345

      - name: Show cache result
        run: echo "Cache hit? ${{ steps.prime-cache-605c345.outputs.cache-hit }}"
